name: testobs
OTA: testota
location_file: location.yaml
states_file: states.yaml
transitions_file: transitions.yaml
initial_state: sleeping

lat: 20.028790056
lon: -155.714876639
height: 677

max_allowed_errors: 1
waittime: 2
maxwait: 10
datadir: ../data/

weather: simulator
roof: simulator
telescope: simulator
instrument: simulator
detector: simulator

loglevel_console: info
loglevel_file: debug
logfile: null
