name: hokuula
location_file: location.yaml
states_file: states.yaml
transitions_file: transitions.yaml
initial_state: sleeping
max_allowed_errors: 1
waittime: 2
maxwait: 10

weather: simulator
roof: simulator
telescope: simulator
instrument: simulator
detector: simulator
