name: hokuula
location_file: location.yaml
states_file: states.yaml
transitions_file: transitions.yaml
initial_state: sleeping
max_allowed_errors: 1
waittime: 2
maxwait: 10

# filename
file_basename: img
file_startno: 0
file_ndigits: 4

weather: simulator
roof: simulator
telescope: simulator
instrument: simulator
detector: simulator
