- name: sleeping
  on_enter:
  - entry_timestamp
  on_exit:
  - exit_timestamp
  ignore_invalid_triggers: null
- name: waiting
  on_enter:
  - entry_timestamp
  - wait_for
  on_exit:
  - exit_timestamp
  ignore_invalid_triggers: null
- name: opening
  on_enter:
  - entry_timestamp
  - open_roof
  on_exit:
  - exit_timestamp
  ignore_invalid_triggers: null
- name: scheduling
  on_enter:
  - entry_timestamp
  - get_OB
  on_exit:
  - exit_timestamp
  ignore_invalid_triggers: null
- name: acquiring
  on_enter:
  - entry_timestamp
  - slew_telescope
  on_exit:
  - exit_timestamp
  ignore_invalid_triggers: null
- name: configuring
  on_enter:
  - entry_timestamp
  - configure_instrument
  on_exit:
  - exit_timestamp
  ignore_invalid_triggers: null
- name: observing
  on_enter:
  - entry_timestamp
  - begin_observation
  on_exit:
  - exit_timestamp
  ignore_invalid_triggers: null
- name: closing
  on_enter:
  - entry_timestamp
  - close_roof
  on_exit:
  - exit_timestamp
  ignore_invalid_triggers: null
- name: pau
  on_enter:
  - entry_timestamp
  on_exit:
  - exit_timestamp
  ignore_invalid_triggers: null
- name: alert
  on_enter:
  - entry_timestamp
  on_exit:
  - exit_timestamp
  ignore_invalid_triggers: null
