# Wake Up
- trigger: wake_up
  source: sleeping
  dest: alert
  conditions: [roof_err]
- trigger: wake_up
  source: sleeping
  dest: waiting_closed
  conditions: []

# Done Waiting
- trigger: done_waiting
  source: waiting_closed
  dest: pau
  conditions: [done_observing]
- trigger: done_waiting
  source: waiting_closed
  dest: opening
  conditions: [ready_to_open]
- trigger: done_waiting
  source: waiting_closed
  dest: waiting_closed
  conditions: []

# Done Opening
- trigger: done_opening
  source: opening
  dest: closing
  conditions: [roof_err]
- trigger: done_opening
  source: opening
  dest: waiting_open
  conditions: []

# Acquire
- trigger: acquire
  source: waiting_open
  dest: closing
  conditions: [done_observing]
- trigger: acquire
  source: waiting_open
  dest: closing
  conditions: [long_wait]
- trigger: acquire
  source: waiting_open
  dest: waiting_open
  conditions: [no_target]
- trigger: acquire
  source: waiting_open
  dest: waiting_open
  conditions: [below_horizon]
- trigger: acquire
  source: waiting_open
  dest: acquiring
  conditions: []

# Done Acquiring
- trigger: done_acquiring
  source: acquiring
  dest: configuring
  conditions: []
- trigger: done_acquiring
  source: acquiring
  dest: waiting_open
  conditions: [acquisition_failed]

# Start Observation
- trigger: start_observation
  source: configuring
  dest: focusing
  conditions: [focus_next]
- trigger: start_observation
  source: configuring
  dest: observing
  conditions: []

# Observation Complete
- trigger: observation_complete
  source: observing
  dest: waiting_open
  conditions: []

# Focusing Complete
- trigger: focusing_complete
  source: focusing
  dest: waiting_open
  conditions: []
- trigger: focusing_complete
  source: focusing
  dest: focusing
  conditions: [focus_failed]

# Done Closing
- trigger: done_closing
  source: closing
  dest: alert
  conditions: [roof_err]
- trigger: done_closing
  source: closing
  dest: pau
  conditions: [done_observing]
- trigger: done_closing
  source: closing
  dest: waiting_closed
  conditions: []



#- trigger: shutdown
#  source: closing
#  dest: pau
#  conditions: []

#- trigger: wait_open
#  source: scheduling
#  dest: waiting_open
#  conditions: []
#- trigger: wait_closed
#  source: closing
#  dest: waiting_closed
#  conditions: []
#
## Failures
#- trigger: failed_opening
#  source: opening
#  dest: closing
#  conditions: []
#- trigger: failed_acquisition
#  source: acquiring
#  dest: scheduling
#  conditions: []
#- trigger: failed_slew
#  source: acquiring
#  dest: scheduling
#  conditions: []
#- trigger: failed_to_configure
#  source: configuring
#  dest: closing
#  conditions: []
#- trigger: failed_observation
#  source: observing
#  dest: scheduling
#  conditions: []
#- trigger: critical_failure
#  source: closing
#  dest: alert
#  conditions: []
#
## Unsafe
#- trigger: unsafe
#  source: [opening, scheduling, acquiring, configuring, observing, waiting_open]
#  dest: closing
#  conditions: []
