# Roof
roof_time_to_open: 5
roof_time_to_close: 5
open_fail_after: null
open_random_fail_rate: 0
close_fail_after: null
close_random_fail_rate: 0

# Telescope
slew_fail_after: null
slew_random_fail_rate: 0
park_fail_after: null
park_random_fail_rate: 0

# Instrument
configure_fail_after: null
configure_random_fail_rate: 0

# Detector
exposure_overhead: 5
expose_fail_after: null
expose_random_fail_rate: 0
